#!/bin/bash

# ************install script**************************************************
#
# This will install correct version of powershell. No dependencies should be
# be required.
#
# This should be ran as root, so that it can make pwsh-preview an exectuable.
#
# This will also run install.ps1, which will install commands in /usr/bin
# so that they can be open from any terminal. To see list of commands
# run command 'get help' after running this script.
#
# This is independent of swarm.ps1 in case user attempts to start swarm
# not as a root user. I however cannot gurantee miners will work, nor will
# they not have issues if they attempt to run swarm not as root.
# *******************************************************************************

## If powershell doesn't exist- Assume it is a first time run.
if ! [ -x "$(command -v pwsh-preview)" ]; then
echo 'pwsh-preview not found- installing 7.0.0-rc.3'
wget https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-rc.3/powershell-7.0.0-rc.3-linux-x64.tar.gz -O /tmp/powershell.tar.gz --no-check-certificate
mkdir -p /opt/microsoft/powershell/7.0.0-rc.3
tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7.0.0-rc.3
chmod +x /opt/microsoft/powershell/7.0.0-rc.3/pwsh-preview
ln -s /opt/microsoft/powershell/7.0.0-rc.3/pwsh-preview /usr/bin/pwsh-preview
rm -rf /tmp/powershell.tar.gz
chmod 777 -R $HOME/.local/share/powershell
fi

PVERSION=`pwsh-preview -version`

## If pwsh-preview is wrong version, install it again.
if [ "$PVERSION" != "PowerShell 7.0.0-rc.3" ]; then
echo "updating powershell to latest version"
rm -rf /opt/microsoft/powershell/
rm -rf /usr/bin/pwsh
wget https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-rc.3/powershell-7.0.0-rc.3-linux-x64.tar.gz -O /tmp/powershell.tar.gz --no-check-certificate
mkdir -p /opt/microsoft/powershell/7.0.0-rc.3
tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7.0.0-rc.3
chmod +x /opt/microsoft/powershell/7.0.0-rc.3/pwsh-preview
ln -s /opt/microsoft/powershell/7.0.0-rc.3/pwsh-preview /usr/bin/pwsh-preview
rm -rf /tmp/powershell.tar.gz
fi

## Run install script per command request.
echo 'starting install script'
pwsh-preview -command ".\build\powershell\scripts\install.ps1"
