#!/bin/bash
screen -S miner -m pwsh -command "&.\swarm.ps1 -HiveOS No -Timeout 24 -Benchmark 160 -RigName1 MMHash -StatsInterval 1 -Currency USD -CoinExchange RVN -Interval 300 -Location US -PoolName nicehash,blockmasters,ahashpool,zpool -Type AMD1 -Wallet1 1DRxiWx6yuZfN9hrEJa3BDXWVJ9yyJU36i -Nicehash_Wallet1 3JfBiUZZV17DTjAFCnZb97UpBgtLPLLDop -PasswordCurrency1 BTC -Nicehash_Fee 2 -Donate .5"
